Repository paparazzi/paparazzi, pull requests merged in 2018-03, with the labels that each got.

#2240 suggestion to make command laws more flexible
  conf/airframes/ENAC/cyfoam.xml
  sw/airborne/subsystems/radio_control.h
Labels: Refactoring

#2244 [build] try to improve dependency and not do unnecessary things
  Makefile.ac
Labels: Build system

#2246 [swarm] add formation control for rotorcraft
  conf/abi.xml
  conf/joystick/T1600M_ground.xml
  conf/modules/fc_rotor.xml
  conf/modules/guidance_indi.xml
  conf/swarm/conf_2uav_rot.json
  conf/swarm/conf_3uav_rot.json
  sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c
  sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.h
  sw/airborne/modules/fc_rotor/fc_rotor.c
  sw/airborne/modules/fc_rotor/fc_rotor.h
  sw/airborne/subsystems/abi_sender_ids.h
  sw/airborne/subsystems/ins/ins_gps_passthrough.c
  sw/ground_segment/joystick/input2ivy.ml
  sw/ground_segment/python/fc_rotor/fc_rotor.py
  sw/ground_segment/python/fc_rotor/lib_rigid_formations.py
  sw/ground_segment/python/natnet3.x/NatNetClient.py
  sw/ground_segment/python/natnet3.x/natnet2ivy.py
Labels: Airborne, Ground Segment, Module, Rotorcraft

#2247 [doc] start sphynx doc for paparazzi
  doc/sphinx/Makefile
  doc/sphinx/source/conf.py
  doc/sphinx/source/developer_guide/developer2.rst
  doc/sphinx/source/developer_guide/index_developer.rst
  doc/sphinx/source/developer_guide/system_overview.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/installation/hardware/airframes/fixed_wing.rst
  doc/sphinx/source/installation/hardware/airframes/index_airframes.rst
  doc/sphinx/source/installation/hardware/airframes/rotorcraft.rst
  doc/sphinx/source/installation/hardware/airframes/vtol.rst
  doc/sphinx/source/installation/hardware/autopilots/apogee.rst
  doc/sphinx/source/installation/hardware/autopilots/chimera.rst
  doc/sphinx/source/installation/hardware/autopilots/index_autopilots.rst
  doc/sphinx/source/installation/hardware/index_hardware.rst
  doc/sphinx/source/installation/index_installation.rst
  doc/sphinx/source/installation/software/index_software.rst
  doc/sphinx/source/installation/software/linux.rst
  doc/sphinx/source/installation/software/mac_os.rst
  doc/sphinx/source/installation/software/windows.rst
  doc/sphinx/source/quickstart/first_flight.rst
  doc/sphinx/source/quickstart/first_simulation.rst
  doc/sphinx/source/quickstart/index_start.rst
  doc/sphinx/source/quickstart/install.rst
  doc/sphinx/source/support/faq.rst
  doc/sphinx/source/support/forum.rst
  doc/sphinx/source/support/index_support.rst
  doc/sphinx/source/support/wiki.rst
  doc/sphinx/source/tutorials/advanced/index_advanced.rst
  doc/sphinx/source/tutorials/beginner/add_drones.rst
  doc/sphinx/source/tutorials/beginner/airframe_setup.rst
  doc/sphinx/source/tutorials/beginner/flight_plan_setup.rst
  doc/sphinx/source/tutorials/beginner/gcs_setup.rst
  doc/sphinx/source/tutorials/beginner/index_beginner.rst
  doc/sphinx/source/tutorials/beginner/sensor_calibration.rst
  doc/sphinx/source/tutorials/beginner/testing_and_tuning.rst
  doc/sphinx/source/tutorials/index_tutorials.rst
  doc/sphinx/source/tutorials/intermediate/index_intermediate.rst
  doc/sphinx/source/tutorials/intermediate/write_module.rst
  doc/sphinx/source/user_guide/hardware/airframes.rst
  doc/sphinx/source/user_guide/hardware/electronics.rst
  doc/sphinx/source/user_guide/hardware/index_hardware.rst
  doc/sphinx/source/user_guide/hardware/sensors.rst
  doc/sphinx/source/user_guide/index_user_guide.rst
  doc/sphinx/source/user_guide/software/airframe_conf.rst
  doc/sphinx/source/user_guide/software/architecture.rst
  doc/sphinx/source/user_guide/software/flashing.rst
  doc/sphinx/source/user_guide/software/gcs.rst
  doc/sphinx/source/user_guide/software/help_software.rst
  doc/sphinx/source/user_guide/software/index_software.rst
  doc/sphinx/source/user_guide/software/logs.rst
  doc/sphinx/source/user_guide/software/pprz_center.rst
  doc/sphinx/source/user_guide/software/simulation.rst
  doc/sphinx/source/user_guide/software/tuning.rst
  doc/sphinx/source/user_guide/system_overview/system_overview.rst
Labels: Documentation
