Repository paparazzi/paparazzi, pull requests merged in 2019-12, with the labels that each got.

#2472 [build] fix build dep for tools
  Makefile
  sw/lib/ocaml/Makefile
Labels: Build system

#2477 Added RTCM moving baseline messages and extended amount of GPS channels
  sw/airborne/modules/gps/gps_ubx_ucenter.c
  sw/airborne/subsystems/gps.c
  sw/airborne/subsystems/gps.h
  sw/airborne/subsystems/gps/gps_ubx.c
  sw/airborne/subsystems/gps/gps_ubx.h
  sw/airborne/subsystems/gps/librtcm3/rtcm3.h
  sw/ground_segment/misc/rtcm2ivy.c
  sw/ground_segment/tmtc/aircraft.ml
Labels: Enhancement, Not a defect, PleaseReviewAndClosePullRequest

#2471 [jevois] move some functionnality to jevois cam driver
  conf/modules/cv_target_localization.xml
  conf/modules/jevois.xml
  sw/airborne/modules/computer_vision/cv_target_localization.c
  sw/airborne/modules/computer_vision/cv_target_localization.h
  sw/airborne/modules/sensors/cameras/jevois.c
  sw/airborne/modules/sensors/cameras/jevois.h
Labels: Airborne, Driver
