Repository paparazzi/paparazzi, pull requests merged in 2020-07, with the labels that each got.

#2543 [module] servo_tester update: automatic sweep option
  conf/modules/servo_tester.xml
  sw/airborne/modules/servo_tester/servo_tester.c
  sw/airborne/modules/servo_tester/servo_tester.h
Labels: Module

#2544 System identification module
  conf/airframes/tudelft/aa_quadplane.xml
  conf/modules/sys_id_chirp.xml
  conf/userconf/tudelft/conf.xml
  sw/airborne/math/pprz_random.c
  sw/airborne/math/pprz_random.h
  sw/airborne/modules/system_identification/pprz_chirp.c
  sw/airborne/modules/system_identification/pprz_chirp.h
  sw/airborne/modules/system_identification/sys_id_chirp.c
  sw/airborne/modules/system_identification/sys_id_chirp.h
Labels: Module, New Feature

#2539 Compile chibiOS with cpp 11
  conf/Makefile.chibios
  conf/modules/ins_ekf2.xml
Labels: Build system, ChibiOS

#2510 [module] Controller for in the windtunnel to perform step inputs
  conf/modules/ctrl_windtunnel.xml
  sw/airborne/modules/ctrl/ctrl_windtunnel.c
  sw/airborne/modules/ctrl/ctrl_windtunnel.h
Labels: Module

#2549 FIX SoftI2C marking transaction complete before stop bit
  sw/airborne/mcu_periph/softi2c.c
Labels: Airborne, Driver

#2547 [conf] cleaning some airframe files for CI builds
  conf/airframes/AGGIEAIR/aggieair_iris_indi.xml
  conf/airframes/BR/quadshot_asp21_FutabaPPMonUart1.xml
  conf/airframes/ENAC/quadrotor/ard2_base_digit.xml
  conf/airframes/ENAC/quadrotor/ard2_base_vision.xml
  conf/airframes/ENAC/quadrotor/ard2_basic.xml
  conf/airframes/ENAC/quadrotor/ard2_basic_adhoc.xml
  conf/airframes/ENAC/quadrotor/booz2_g1.xml
  conf/airframes/OPENUAS/openuas_eflite_t28.xml
  conf/airframes/OPENUAS/openuas_vivify.xml
  conf/airframes/tudelft/iris_indi.xml
  conf/airframes/tudelft/mentor.xml
  conf/airframes/tudelft/robird.xml
Labels: conf

#2553 Fix modules and telemetry freq
  conf/modules/extra_dl.xml
  conf/modules/mavlink.xml
  sw/tools/generators/gen_aircraft.ml
  sw/tools/generators/gen_modules.ml
  sw/tools/generators/gen_periodic.ml
Labels: Airborne, Major, bug

#2551 [effectiveness] module and tool to log and process control effectiveness
  conf/modules/logger_control_effectiveness.xml
  sw/airborne/modules/loggers/logger_control_effectiveness.c
  sw/airborne/modules/loggers/logger_control_effectiveness.h
  sw/tools/control_effectiveness/config/quadrotor.json
  sw/tools/control_effectiveness/config/quadrotor_simple_indi.json
  sw/tools/control_effectiveness/control_effectiveness_estimation.py
  sw/tools/control_effectiveness/control_effectiveness_utils.py
Labels: Module

#2550 [rotorcraft] split arming code definition from autopilot
  sw/airborne/firmwares/rotorcraft/autopilot_arming.h
  sw/airborne/firmwares/rotorcraft/autopilot_arming_common.h
  sw/airborne/firmwares/rotorcraft/autopilot_arming_switch.h
  sw/airborne/firmwares/rotorcraft/autopilot_arming_throttle.h
  sw/airborne/firmwares/rotorcraft/autopilot_arming_yaw.h
  sw/airborne/firmwares/rotorcraft/autopilot_generated.c
  sw/airborne/firmwares/rotorcraft/autopilot_static.c
  sw/airborne/firmwares/rotorcraft/autopilot_static.h
Labels: Airborne, Rotorcraft

#2558 Sphinx doc
  doc/sphinx/source/developer_guide/system_overview.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/installation/index_installation.rst
  doc/sphinx/source/installation/software/index_software.rst
  doc/sphinx/source/installation/software/linux.rst
  doc/sphinx/source/quickstart/first_simulation.rst
  doc/sphinx/source/quickstart/gcs.png
  doc/sphinx/source/quickstart/index_start.rst
  doc/sphinx/source/quickstart/install.rst
  doc/sphinx/source/quickstart/paparazzi_center_tour.rst
  doc/sphinx/source/quickstart/pprz_center.png
  doc/sphinx/source/tutorials/beginner/add_drones.rst
  doc/sphinx/source/tutorials/beginner/configuration_capture.png
  doc/sphinx/source/tutorials/beginner/new_ac.png
  doc/sphinx/source/tutorials/index_tutorials.rst
  doc/sphinx/source/tutorials/interfacing_with_paparazzi.rst
  doc/sphinx/source/tutorials/intermediate/create_radio.rst
  doc/sphinx/source/tutorials/intermediate/imu_configuration.rst
  doc/sphinx/source/tutorials/intermediate/index_intermediate.rst
  doc/sphinx/source/tutorials/intermediate/pictures_imu/acc_calibration.jpg
  doc/sphinx/source/tutorials/intermediate/pictures_imu/apogee_imu_axis.png
  doc/sphinx/source/tutorials/intermediate/pictures_imu/plane_axis.png
  doc/sphinx/source/tutorials/intermediate/pictures_imu/raw_sensors.jpg
  doc/sphinx/source/tutorials/intermediate/ppm_messages.png
  doc/sphinx/source/tutorials/intermediate/ppm_mode.png
  doc/sphinx/source/user_guide/software/gcs.rst
  doc/sphinx/source/user_guide/system_overview/system_overview.rst
Labels: Documentation

#2552 Fix dshot and dma
  sw/airborne/arch/chibios/mcu_periph/hal_stm32_dma.c
  sw/airborne/arch/chibios/mcu_periph/hal_stm32_dma.h
  sw/airborne/arch/chibios/modules/actuators/actuators_dshot_arch.c
  sw/airborne/arch/chibios/modules/actuators/esc_dshot.c
  sw/airborne/arch/chibios/modules/actuators/esc_dshot.h
  sw/airborne/boards/chimera/chibios/v1.0/mcuconf.h
Labels: Airborne, Driver
