Repository paparazzi/paparazzi, pull requests merged in 2021-02, with the labels that each got.

#2652 [fix] allow float values for delay in module XML
  conf/modules/MPPT.xml
  conf/modules/alt_srf08.xml
  conf/modules/dust_gp2y.xml
  conf/modules/gsm.xml
  conf/modules/humid_htm_b71.xml
  conf/modules/humid_sht_i2c.xml
  conf/modules/wind_gfi.xml
  sw/lib/ocaml/module.ml
  sw/tools/generators/gen_modules.ml
Labels: Build system, Module

#2659 [ocaml] fix SRTM download path
  data/srtm/srtm.data.bz2
  sw/lib/ocaml/mapCanvas.ml
  sw/lib/ocaml/srtm.ml
  sw/lib/ocaml/srtm.mli
Labels: Ground Segment

#2663 minor fix for macOSX compatibility.
  sw/ground_segment/misc/rtcm2ivy.c
Labels: Minor, Portability

#2665 Fix python comparison.
  sw/simulator/pprzsim-launch
Labels: Minor, Simulation

#2666 [fix] define _fini dummy syscall for chibios
  sw/airborne/pprz_syscalls.c
Labels: ChibiOS, Minor, bug
