Repository paparazzi/paparazzi, pull requests merged in 2022-10, with the labels that each got.

#2912 [imu] fix old config compat for axis signs
  sw/airborne/modules/imu/imu.c
Labels: bug

#2915 Fix imu conf
  sw/airborne/modules/ahrs/ahrs_aligner.c
  sw/airborne/modules/ahrs/ahrs_float_cmpl_wrapper.c
  sw/airborne/modules/ahrs/ahrs_float_dcm_wrapper.c
  sw/airborne/modules/ahrs/ahrs_float_invariant_wrapper.c
  sw/airborne/modules/ahrs/ahrs_float_mlkf_wrapper.c
  sw/airborne/modules/ahrs/ahrs_int_cmpl_quat_wrapper.c
  sw/airborne/modules/ahrs/ahrs_madgwick_wrapper.c
  sw/airborne/modules/core/abi_sender_ids.h
  sw/airborne/modules/imu/filter_1euro_imu.c
  sw/airborne/modules/imu/imu.c
  sw/airborne/modules/ins/ins_float_invariant_wrapper.c
  sw/airborne/modules/ins/ins_mekf_wind_wrapper.c
Labels: bug

#2897 [board] Fix chibios common i2c and pwm input
  sw/airborne/arch/chibios/common_board.h
  sw/airborne/boards/px4fmu/chibios/v5.0/board.cfg
  sw/airborne/boards/px4fmu/chibios/v5.0/board.h
Labels: ChibiOS, bug

#2927 [autopilot] fix detection of generated mode and generation dep
  sw/ground_segment/tmtc/aircraft_server.ml
  sw/ground_segment/tmtc/server.ml
  sw/ground_segment/tmtc/server_globals.ml
  sw/tools/generators/gen_aircraft.ml
Labels: Ground Segment, Build system

#2896 GVF user configs and GVF Viewer documentation
  Makefile
  conf/airframes/UCM/sonic2.xml
  conf/userconf/GVF/gvf_conf.xml
  doc/sphinx/source/user_guide/gvf_classic.png
  doc/sphinx/source/user_guide/gvf_parametric.png
  doc/sphinx/source/user_guide/gvf_viewer.rst
  doc/sphinx/source/user_guide/gvf_viewer_layout.png
  doc/sphinx/source/user_guide/gvf_viewer_showcase.png
  doc/sphinx/source/user_guide/index_user_guide.rst
Labels: Documentation

#2924 Ublox GPS - Manual hot, warm and cold reset functionality
  conf/modules/gps_ublox.xml
  sw/airborne/modules/gps/gps_ubx.c
  sw/airborne/modules/gps/gps_ubx.h
Labels: Driver

#2930 [ins] enable nav init for EKF2 by default
  sw/airborne/modules/ins/ins_ekf2.cpp
Labels: Airborne

#2931 Tag tracking speed integration
  conf/airframes/ENAC/rover_ostrich.xml
  conf/flight_plans/ENAC/demo_aruco_drop_indoor.xml
  conf/flight_plans/flight_plan.dtd
  conf/flight_plans/rotorcraft_guided_demo.xml
  conf/modules/tag_tracking.xml
  sw/airborne/firmwares/rotorcraft/autopilot_guided.c
  sw/airborne/firmwares/rotorcraft/autopilot_guided.h
  sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
  sw/airborne/firmwares/rotorcraft/guidance/guidance_h.h
  sw/airborne/firmwares/rotorcraft/guidance/guidance_v.c
  sw/airborne/firmwares/rotorcraft/guidance/guidance_v.h
  sw/airborne/firmwares/rotorcraft/navigation.h
  sw/airborne/modules/computer_vision/tag_tracking.c
  sw/airborne/modules/computer_vision/tag_tracking.h
  sw/airborne/modules/orange_avoider/orange_avoider_guided.c
  sw/airborne/modules/wedgebug/wedgebug.c
  sw/include/std.h
  sw/tools/generators/gen_flight_plan.ml
Labels: Airborne, Rotorcraft, Module, Flight Plan

#2933 [nps] variables in nps_main should be extern
  sw/simulator/nps/nps_ivy.c
  sw/simulator/nps/nps_ivy.h
  sw/simulator/nps/nps_main.h
  sw/simulator/nps/nps_main_common.c
Labels: Simulation

#2937 [nps] Fix IMU and MAG signs.
  conf/simulator/nps/nps_sensors_params_common.h
  conf/simulator/nps/nps_sensors_params_default.h
  conf/simulator/nps/nps_sensors_params_noisy.h
  sw/airborne/modules/imu/imu_nps.c
Labels: Simulation

#2939 [gps] fix parsing of PVT heading
  sw/airborne/modules/gps/gps_ubx.c
Labels: Driver, bug
