Repository paparazzi/paparazzi, pull requests merged in 2022-04, with the labels that each got.

#2852 [makefile] Remove ffast-math compiler flags
  conf/Makefile.arm-linux
  conf/Makefile.linux
  conf/Makefile.stm32
Labels: bug

#2860 [chibios] Make constants consistent with different architectures
  conf/boards/holybro_kakute_f7.makefile
  conf/chibios/chibios_rules.mk
Labels: Airborne, ChibiOS

#2864 [doc] suggest install of PprzGCS.
  doc/sphinx/source/quickstart/install.rst
Labels: Documentation

#2867 [supervision] Fix Makefile.
  sw/supervision/python/Makefile
Labels: Build system

#2866 Doc flight plan
  doc/sphinx/source/user_guide/flight_plans.rst
  doc/sphinx/source/user_guide/pprz_flight_plan.png
Labels: Documentation

#2868 [ariframe] sample bebop with 2x 30Hz optic flow:
  conf/airframes/tudelft/bebop_opticflow_indoor_2x_30hz.xml
  conf/userconf/tudelft/conf.xml
Labels: conf

#2869 [doc] documentation for the general architecture
  doc/sphinx/source/developer_guide/PPRZ_Airborne_architecture.png
  doc/sphinx/source/developer_guide/PPRZ_Low_level_architecture.png
  doc/sphinx/source/developer_guide/PPRZ_Main_ap_loop.png
  doc/sphinx/source/developer_guide/PPRZ_System_architecture.png
  doc/sphinx/source/developer_guide/agents_arch.png
  doc/sphinx/source/developer_guide/airborne_arch.png
  doc/sphinx/source/developer_guide/general_arch.png
  doc/sphinx/source/developer_guide/system_overview.rst
  doc/sphinx/source/quickstart/PPRZ_System_architecture.png
  doc/sphinx/source/quickstart/agents_arch.png
  doc/sphinx/source/quickstart/system_overview.rst
Labels: Documentation

#2873 [indi] only calculate command if in flight
  sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
Labels: Minor
