Repository paparazzi/paparazzi, pull requests merged in 2022-03, with the labels that each got.

#2834 [python lib] small fix for the python flight plan lib.
  sw/lib/python/flight_plan.py
Labels: Ground Segment

#2831 [gps] Update ublox RTK support and ground tool
  .gitignore
  sw/airborne/modules/gps/gps_ubx.c
  sw/ground_segment/misc/Makefile
  sw/ground_segment/misc/ublox2ivy.c
  sw/ground_segment/misc/ublox2ivy.h
Labels: Ground Segment, Airborne, Driver

#2835 [fix] protect ivy operations with mutex in nps
  sw/simulator/nps/nps_ivy.c
  sw/simulator/nps/nps_main_common.c
Labels: Simulation

#2838 [datalink] move all hardcoded message parsing to modules datalink events
  conf/modules/air_data.xml
  conf/modules/autopilot_gnc.xml
  conf/modules/autopilot_guided.xml
  conf/modules/datalink_common.xml
  conf/modules/gps.xml
  conf/modules/gps_ublox.xml
  conf/modules/nav_basic_fw.xml
  conf/modules/nav_basic_rotorcraft.xml
  conf/modules/nav_rover_base.xml
  conf/modules/radio_control_datalink.xml
  conf/modules/settings.xml
  sw/airborne/firmwares/fixedwing/fixedwing_datalink.c
  sw/airborne/firmwares/fixedwing/nav.c
  sw/airborne/firmwares/fixedwing/nav.h
  sw/airborne/firmwares/rotorcraft/autopilot_guided.c
  sw/airborne/firmwares/rotorcraft/autopilot_guided.h
  sw/airborne/firmwares/rotorcraft/navigation.c
  sw/airborne/firmwares/rotorcraft/navigation.h
  sw/airborne/firmwares/rotorcraft/rotorcraft_datalink.c
  sw/airborne/firmwares/rover/navigation.c
  sw/airborne/firmwares/rover/navigation.h
  sw/airborne/firmwares/rover/rover_datalink.c
  sw/airborne/modules/air_data/air_data.c
  sw/airborne/modules/air_data/air_data.h
  sw/airborne/modules/core/settings.c
  sw/airborne/modules/core/settings.h
  sw/airborne/modules/datalink/datalink.c
  sw/airborne/modules/datalink/datalink.h
  sw/airborne/modules/gps/gps.c
  sw/airborne/modules/gps/gps.h
  sw/airborne/modules/gps/gps_ubx.c
  sw/airborne/modules/gps/gps_ubx.h
  sw/airborne/modules/radio_control/rc_datalink.c
  sw/airborne/modules/radio_control/rc_datalink.h
Labels: Airborne, Module, Rotorcraft and FW convergence

#2841 [fix] collection of fixes after AP/FBW merge
  conf/airframes/AGGIEAIR/aggieair_iris_indi.xml
  conf/airframes/OPENUAS/openuas_df_mini_spirit.xml
  conf/airframes/OPENUAS/openuas_durafly_g2.xml
  conf/airframes/OPENUAS/openuas_durafly_goblin.xml
  conf/airframes/OPENUAS/openuas_eflite_t28.xml
  conf/airframes/OPENUAS/openuas_multiplex_minimag.xml
  conf/airframes/OPENUAS/openuas_multiplex_twinstar_nd.xml
  conf/airframes/OPENUAS/openuas_own_flexo.xml
  conf/airframes/OPENUAS/openuas_own_sumo_ii.xml
  conf/airframes/OPENUAS/openuas_own_vivify.xml
  conf/airframes/OPENUAS/openuas_parrot_disco.xml
  conf/airframes/OPENUAS/openuas_wltech_xk_a160.xml
  conf/airframes/tudelft/disco_modified.xml
  conf/airframes/tudelft/iris_indi.xml
  conf/airframes/tudelft/logo600.xml
  conf/airframes/tudelft/outback.xml
  conf/airframes/tudelft/robird.xml
  conf/airframes/tudelft/twoseastwenty.xml
  conf/autopilot/fixedwing_autopilot.xml
  conf/autopilot/fixedwing_rusty.xml
  conf/flight_plans/OPENUAS/include_obc2014_mission.xml
  conf/flight_plans/OPENUAS/include_obc2014_testing.xml
  conf/flight_plans/OPENUAS/openuas_versatile_unified.xml
  conf/modules/system_core.xml
  conf/settings/control/ctl_adaptive.xml
  conf/settings/control/ctl_basic.xml
  conf/settings/control/ctl_energy.xml
  conf/settings/control/ctl_energyadaptive.xml
  conf/settings/control/ctl_new.xml
  conf/settings/control/ctl_new_airspeed.xml
  sw/airborne/arch/sim/modules/radio_control/spektrum_arch.c
  sw/airborne/arch/sim/modules/radio_control/spektrum_arch.h
  sw/airborne/firmwares/fixedwing/nav.h
  sw/airborne/main_fbw.c
  sw/airborne/modules/actuators/actuators.c
  sw/airborne/modules/core/commands.h
  sw/airborne/modules/datalink/telemetry.c
  sw/airborne/modules/nav/common_flight_plan.h
  sw/airborne/modules/px4_gimbal/px4_gimbal.c
  sw/airborne/modules/radio_control/spektrum.h
  sw/airborne/modules/switching/auto1_commands.c
  sw/include/std.h
  sw/tools/generators/gen_flight_plan.ml
Labels: bug

#2843 [fix] remove ins_neutrals settings file
  conf/conf_tests.xml
  conf/conf_tests_coverity.xml
  conf/modules/ins_xsens700.xml
  conf/settings/estimation/ins_neutrals.xml
  conf/userconf/tudelft/conf.xml
Labels: Minor, bug

#2848 more options to get modules list, even without the conf.xml file
  sw/tools/generators/dump_modules_list.ml
Labels: Build system

#2845 Rover steering wheel
  conf/airframes/UCM/rover_steering.xml
  conf/autopilot/rover_steering.xml
  conf/flight_plans/UCM/steering_rover_gvfMission.xml
  conf/flight_plans/UCM/test_ucm_fisicas.xml
  conf/modules/board_matek_f765_car.xml
  conf/modules/fdm_rover.xml
  conf/modules/firmwares/rover.xml
  conf/modules/guidance_rover_steering.xml
  conf/modules/gvf_module.xml
  conf/radios/UCM/T16SZ_SBUS_rover.xml
  sw/airborne/firmwares/rover/guidance/rover_guidance_steering.c
  sw/airborne/firmwares/rover/guidance/rover_guidance_steering.h
  sw/airborne/firmwares/rover/navigation.h
  sw/airborne/modules/guidance/gvf/gvf.c
  sw/simulator/nps/nps_autopilot_rover.c
  sw/simulator/nps/nps_fdm_rover.c
Labels: rover

#2849 [baro] Fix Bebop barometer configuration
  conf/modules/boards/bebop.xml
  conf/modules/boards/bebop2.xml
  conf/modules/boards/disco.xml
  sw/airborne/boards/bebop/baro_board.h
  sw/airborne/boards/disco/baro_board.h
  sw/airborne/modules/sensors/baro_ms5611_i2c.c
Labels: bug

#2850 [ins] Add ekf2 messages
  sw/airborne/firmwares/rotorcraft/guidance/guidance_h_ref.c
  sw/airborne/math/pprz_algebra_int.h
  sw/airborne/modules/ins/ins_ekf2.cpp
Labels: Airborne, communication

#2851 [python] tool to read data from hotwire anemometer PCE-423
  sw/ground_segment/python/anemometer_PCE423.py
Labels: Ground Segment
