Repository paparazzi/paparazzi, pull requests merged in 2022-05, with the labels that each got.

#2876 [sphinx] Improvements to the ABI section
  doc/sphinx/source/developer_guide/abi.rst
Labels: Documentation

#2878 [chibios] usb serial
  conf/modules/logger_sd_chibios.xml
  conf/modules/module.dtd
  conf/modules/shell.xml
  conf/modules/uart.xml
  sw/airborne/arch/chibios/modules/core/microrl/microrlShell.c
  sw/airborne/arch/chibios/modules/core/shell_arch.c
  sw/airborne/arch/chibios/usb_ser_hw.c
  sw/airborne/mcu_periph/usb_serial.h
  sw/airborne/modules/loggers/sdlog_chibios/usbStorage.c
  sw/airborne/modules/loggers/sdlog_chibios/usbStorage.h
Labels: ChibiOS

#2880 [settings] Support functions
  conf/airframes/ENAC/conf_enac.xml
  conf/conf_tests.xml
  conf/modules/boards/apogee_1.0.xml
  conf/modules/boards/apogee_1.0_chibios.xml
  conf/modules/boards/cube_orange.xml
  conf/modules/boards/px4fmu_5.0_chibios.xml
  conf/modules/power_switch.xml
  conf/settings/fixedwing_basic.xml
  conf/settings/power_switch.xml
  conf/settings/rotorcraft_basic.xml
  conf/settings/rotorcraft_basic_multi.xml
  conf/settings/rover_basic.xml
  conf/settings/switchlight.xml
  sw/airborne/arch/chibios/board.c
  sw/airborne/arch/chibios/mcu_arch.c
  sw/airborne/arch/chibios/mcu_arch.h
  sw/airborne/autopilot.c
  sw/airborne/autopilot.h
  sw/airborne/mcu.c
  sw/airborne/mcu.h
  sw/airborne/modules/boards/power_switch.c
  sw/airborne/modules/boards/power_switch.h
  sw/airborne/modules/loggers/sdlog_chibios.c
  sw/airborne/modules/loggers/sdlog_chibios/usbStorage.c
  sw/tools/generators/gen_settings.ml
Labels: Module, New Feature

#2872 [sphinx] addition of library page
  doc/sphinx/source/developer_guide/modules.rst
Labels: Documentation

#2882 [sphinx] Adds Logging section in Developer Guide
  doc/sphinx/source/developer_guide/index_developer.rst
  doc/sphinx/source/developer_guide/logging.rst
Labels: Documentation
