Repository paparazzi/paparazzi, pull requests merged in 2023-12, with the labels that each got.

#3194 [pwm] use different names to activate PWM drivers in chibios and pprz
  sw/airborne/arch/chibios/modules/actuators/actuators_pwm_arch.c
  sw/airborne/boards/apogee/chibios/v1.0/board.cfg
  sw/airborne/boards/apogee/chibios/v1.0/board.h
  sw/airborne/boards/chimera/chibios/v1.0/chimera.h
  sw/airborne/boards/crazyflie/chibios/v2.1/crazyflie.h
  sw/airborne/boards/cube/orange/board.cfg
  sw/airborne/boards/cube/orange/board.h
  sw/airborne/boards/holybro/kakute_f7/holybro_kakute_f7.h
  sw/airborne/boards/lia/chibios/v1.1/board.h
  sw/airborne/boards/lisa_mx/chibios/v2.1/board.h
  sw/airborne/boards/lisa_mxs/chibios/v1.0/board.h
  sw/airborne/boards/mateksys/F765-WING/matekF765-WING.h
  sw/airborne/boards/mateksys/FC-H743-SLIM/board.cfg
  sw/airborne/boards/mateksys/FC-H743-SLIM/board.h
  sw/airborne/boards/nucleo/144_f767zi/nucleo144_f767zi.h
  sw/airborne/boards/px4fmu/chibios/v2.4/board.h
  sw/airborne/boards/px4fmu/chibios/v4.0/px4fmu.h
  sw/airborne/boards/px4fmu/chibios/v5.0/board.cfg
  sw/airborne/boards/px4fmu/chibios/v5.0/board.h
  sw/airborne/boards/tawaki/chibios/common/tawaki.h
Labels: Driver, bug

#3193 [checks] Add IMU heater preflight check and fix minor bugs
  conf/modules/imu_heater.xml
  sw/airborne/modules/checks/preflight_checks.c
  sw/airborne/modules/imu/imu_heater.c
  sw/airborne/modules/loggers/sdlog_chibios.c
Labels: Minor, bug

#3195 [fix] fix some bugs from #3190
  conf/conf_tests.xml
  sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c
  sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
  sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.c
Labels: bug

#3196 Fix continuous actuator
  sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c
  sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
  sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.c
Labels: Blocking

#3200 [fix] use variable instead of macro for thrust dyn in guidance_indi
  sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c
Labels: bug

#3209 [boards] fix pwm timer enabled for lisa_mx[s] boards with chibios
  sw/airborne/boards/lisa_mx/chibios/v2.1/board.h
  sw/airborne/boards/lisa_mxs/chibios/v1.0/board.h
Labels: Airborne, ChibiOS, bug

#3211 [imu] simulating 3 IMU's failed since an NPS IMU is added
  sw/airborne/modules/imu/imu.h
Labels: Simulation, bug

#3208 Remove command_pitch and command_roll and command_yaw
  conf/airframes/tudelft/rot_wing_v3d.xml
  sw/airborne/firmwares/rotorcraft/autopilot_firmware.c
  sw/airborne/firmwares/rotorcraft/autopilot_utils.c
  sw/airborne/firmwares/rotorcraft/guidance/guidance_flip.c
  sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
  sw/airborne/firmwares/rotorcraft/stabilization/stabilization_none.c
Labels: Airborne

#2497 [link] Pprzlink router (for herelink)
  .gitignore
  sw/misc/link/Makefile
  sw/misc/link/mass_storage.sh
  sw/misc/link/pprzlink_router.c
  sw/misc/link/pprzlink_router.md
Labels: communication

#3222 [fix] nominal throttle was not initialised
  sw/airborne/firmwares/rotorcraft/guidance/guidance_v.c
Labels: Airborne, bug

#3223 Enac conf cleaning
  conf/airframes/ENAC/conf_enac.xml
  conf/airframes/ENAC/fixed-wing/chimera.xml
  conf/airframes/ENAC/fixed-wing/crrcsim.xml
  conf/airframes/ENAC/fixed-wing/panache_1.xml
  conf/airframes/ENAC/fixed-wing/zagi_test.xml
  conf/airframes/ENAC/hoops_gen_ap.xml
  conf/airframes/ENAC/hybrid/cyfoam.xml
  conf/airframes/ENAC/hybrid/falcon_v1.xml
  conf/airframes/ENAC/hybrid/falcon_v2.xml
  conf/airframes/ENAC/quadrotor/ard2_101.xml
  conf/airframes/ENAC/quadrotor/ard2_103.xml
  conf/airframes/ENAC/quadrotor/ard2_104.xml
  conf/airframes/ENAC/quadrotor/ard2_base_control.xml
  conf/airframes/ENAC/quadrotor/ard2_base_digit.xml
  conf/airframes/ENAC/quadrotor/ard2_base_vision.xml
  conf/airframes/ENAC/quadrotor/ard2_basic.xml
  conf/airframes/ENAC/quadrotor/ard2_basic_adhoc.xml
  conf/airframes/ENAC/quadrotor/drop1.xml
  conf/airframes/ENAC/quadrotor/maya_indoor.xml
  conf/airframes/ENAC/quadrotor/maya_outdoor.xml
  conf/airframes/ENAC/rover/rover_2_wheels.xml
  conf/airframes/ENAC/rover/rover_ostrich.xml
  conf/airframes/matek_f405_wing/Easyglider_matek_f405_wing.xml
  conf/airframes/test_boards/apogee.xml
  conf/airframes/test_boards/chimera.xml
  conf/airframes/test_boards/conf_test_boards.xml
  conf/airframes/test_boards/crazyflie_2.1.xml
  conf/airframes/test_boards/disco.xml
  conf/airframes/test_boards/kakute_f7.xml
  conf/airframes/test_boards/matek_f405_wing.xml
  conf/airframes/test_boards/matek_f765_wing.xml
  conf/airframes/test_boards/matek_h743_slim.xml
  conf/airframes/test_boards/nucleo144.xml
  conf/airframes/test_boards/tawaki.xml
  conf/conf_tests.xml
  conf/conf_tests_coverity.xml
  conf/mag/germany_aachen.xml
Labels: conf
