Repository paparazzi/paparazzi, pull requests merged in 2025-03, with the labels that each got.

#3436 [generator] add global node for selection of modes in gen_autopilot
  conf/autopilot/autopilot.dtd
  conf/autopilot/rotorcraft_autopilot.xml
  sw/tools/generators/gen_autopilot.ml
Labels: Airborne, Build system

#3439 Doc mission mode
  doc/sphinx/requirements.txt
  doc/sphinx/source/conf.py
  doc/sphinx/source/user_guide/index_user_guide.rst
  doc/sphinx/source/user_guide/mission_mode.png
  doc/sphinx/source/user_guide/mission_mode.rst
Labels: Documentation

#3441 [doc] Update install instructions.
  doc/sphinx/source/getting_started/install.rst
Labels: Documentation

#3442 [guided] rewrite guided mode example with a separated lib
  sw/ground_segment/python/guided_mode_example.py
  sw/lib/python/guided_mode.py
  sw/lib/python/settings.py
Labels: Ground Segment

#3444 [ext] test for em module needed by dronecan
  requirements.txt
  sw/ext/Makefile
  sw/ext/dronecan/Makefile
Labels: Build system

#3443 [ins] Properly initialize utm0 altitude in ins_alt_float
  sw/airborne/modules/ins/ins_alt_float.c
Labels: Airborne, bug
