Repository paparazzi/paparazzi, pull requests merged in 2025-07, with the labels that each got.

#3495 [imu] fix some bugs introduced with imu float refactor
  sw/airborne/boards/ardrone/navdata.c
  sw/airborne/modules/imu/imu.c
  sw/airborne/modules/imu/imu.h
  sw/airborne/modules/imu/imu_aspirin.c
  sw/airborne/modules/imu/imu_aspirin_i2c.c
  sw/airborne/modules/imu/imu_cube.c
  sw/airborne/modules/imu/imu_nps.c
  sw/airborne/modules/imu/imu_px4fmu_v2.4.c
  sw/airborne/modules/sensors/sensors_hitl.c
  sw/airborne/peripherals/bmi088.c
  sw/airborne/peripherals/bmi088.h
  sw/airborne/peripherals/invensense2.c
  sw/airborne/peripherals/invensense3.c
  sw/airborne/peripherals/mpu60x0.c
  sw/airborne/peripherals/mpu60x0.h
  sw/airborne/peripherals/mpu9250.c
  sw/airborne/peripherals/mpu9250.h
Labels: bug

#3498 [fix] don't use pointer cast to switch between Vect3 and Coord structures
  sw/airborne/modules/ins/ins_alt_float.c
  sw/airborne/modules/ins/ins_float_invariant.c
  sw/airborne/modules/ins/ins_gps_passthrough.c
Labels: Airborne, bug

#3499 Fix warning of nested extern declaration of fn get_sys_time_float
  sw/airborne/arch/stm32/modules/core/threads_arch.c
Labels: Minor
