Repository paparazzi/paparazzi, pull requests merged in 2025-01, with the labels that each got.

#3395 Start of documentation for adding boards
  doc/sphinx/source/developer_guide/index_developer.rst
  doc/sphinx/source/developer_guide/new_board.rst
Labels: Documentation

#3418 [TawakiV2] Add UART4 on AUX_A1/A2
  sw/airborne/boards/tawaki/chibios/v2.0/board.h
  sw/airborne/boards/tawaki/chibios/v2.0/mcuconf_board.h
  sw/airborne/boards/tawaki/chibios/v2.0/tawaki_2.0.cfg
Labels: board config

#3420 [ins] fix reset_ref for ins_alt and fixedwing nav
  sw/airborne/modules/ins/ins_alt_float.c
  sw/airborne/modules/nav/common_nav.c
Labels: Airborne, bug

#3421 [makefile] don't build mavlink if required packages are missing
  sw/ext/Makefile
Labels: Build system

#3422 [build] check gnomecanvas package before compiling legacy GCS
  sw/ground_segment/cockpit/Makefile
Labels: Build system
